name: CI

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: arch
    container:
      image: node:25-alpine
      options: --privileged

    steps:
      - name: Install Docker CLI
        run: apk add --no-cache docker-cli git ca-certificates

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Extract Version
        id: version_step
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_tag=${GITHUB_REPOSITORY}:$VERSION" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "CURRENT_TIME=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.version}}
          echo ${{steps.version_step.outputs.version_tag}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: vc.maxkaya.com
          username: maxpeterkaya
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1"

      - name: Run GoReleaser
        uses: https://vc.maxkaya.com/workflows/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITEA_TOKEN: ${{ secrets.DOCKER_TOKEN }}