name: CI

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: arch
    container:
      image: node:20-alpine
      options: --privileged

    steps:
      - name: Install Docker CLI
        run: apk add --no-cache docker-cli

      - uses: actions/checkout@v5

      - name: Extract Version
        id: version_step
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_tag=${GITHUB_REPOSITORY}:$VERSION" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "CURRENT_TIME=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.version}}
          echo ${{steps.version_step.outputs.version_tag}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: vc.maxkaya.com
          username: maxpeterkaya
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: PrepareReg Names
        id: read-docker-image-identifiers
        run: |
          echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vc.maxkaya.com/${{env.VERSION_TAG}}
          build-args: |
            VERSION=${{ steps.version_step.outputs.version }}
            VERSION_TAG=${{ steps.version_step.outputs.version_tag }}
            GIT_VERSION=${{ steps.version_step.outputs.version }}
            GIT_COMMIT=${{ env.COMMIT_SHA_SHORT }}
            GIT_DATE=${{ env.CURRENT_TIME }}

  release:
    needs: build
    runs-on: arch

    steps:
      - uses: actions/checkout@v5

      - name: Update CHANGELOG
        id: changelog
        uses: https://vc.maxkaya.com/workflows/changelog-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: 'false'

      - name: update release
        id: update_release
        uses: https://github.com/tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body: ${{ steps.changelog.outputs.changes }}
          release_name: Release ${{ github.ref_name }}